// Generated by scripts/sample/build-opening-sample.mjs; do not edit.
import type { SampleManifest } from "./sample-manifest.ts";

export const OPENING_SAMPLE_MANIFEST: SampleManifest = {
  "id": "zvid-opening",
  "version": "opening-v2",
  "sessionName": "zvid opening sample",
  "creditsUrl": "/samples/opening-v2/CREDITS.md",
  "assets": [
    {
      "id": "zvid-sample:opening-v2:orbit",
      "path": "zvid-sample://opening-v2/orbit.mp4",
      "url": "/samples/opening-v2/orbit.mp4",
      "name": "orbit.mp4",
      "mediaType": "video/mp4",
      "bytes": 5173618,
      "sha256": "699156f81e7863a29077bced76b658656f93d1c2c2423a759b0a63b4326e93b9",
      "credit": "Original procedural motion made for zvid (app/scripts/sample/render_sources.py)."
    },
    {
      "id": "zvid-sample:opening-v2:ribbon",
      "path": "zvid-sample://opening-v2/ribbon.mp4",
      "url": "/samples/opening-v2/ribbon.mp4",
      "name": "ribbon.mp4",
      "mediaType": "video/mp4",
      "bytes": 8441652,
      "sha256": "3fbf91ae3c6c4ab6ccf6bee98e2f8004871f6e06c4dfb483431d8423582dafaa",
      "credit": "Original procedural motion made for zvid (app/scripts/sample/render_sources.py)."
    },
    {
      "id": "zvid-sample:opening-v2:corridor",
      "path": "zvid-sample://opening-v2/corridor.mp4",
      "url": "/samples/opening-v2/corridor.mp4",
      "name": "corridor.mp4",
      "mediaType": "video/mp4",
      "bytes": 1445594,
      "sha256": "d8b730cc0fc9f2dae5f07481c88743f070d689b657fd8392dd0a8463cab961d1",
      "credit": "Original procedural motion made for zvid (app/scripts/sample/render_sources.py)."
    },
    {
      "id": "zvid-sample:opening-v2:music",
      "path": "zvid-sample://opening-v2/just-nasty-30s.m4a",
      "url": "/samples/opening-v2/just-nasty-30s.m4a",
      "name": "just-nasty-30s.m4a",
      "mediaType": "audio/mp4",
      "bytes": 770472,
      "sha256": "ce23eb162c10a03586554a4dd96b475a5028670837a4f3a5547c7304eda3a0ee",
      "credit": "\"Just Nasty\" by Kevin MacLeod (incompetech.com), licensed under CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/). 2:00–2:30 excerpted with a 0.6 s fade-in and 2 s fade-out, synchronized to the sample's graphics."
    },
    {
      "id": "zvid-sample:opening-v2:zvid-logo",
      "path": "zvid-sample://opening-v2/zvid-logo.svg",
      "url": "/samples/opening-v2/zvid-logo.svg",
      "name": "zvid-logo.svg",
      "mediaType": "image/svg+xml",
      "bytes": 990,
      "sha256": "a3a2ce53cd78904b535f70d7e8dda7997e0a2cfadd2cad78b6aa9965da7e4eba",
      "credit": "The zvid logo, zvid's own artwork."
    }
  ]
};
