import {
  DEFAULT_FONT_FAMILY,
  FONT_WEIGHT_LABELS,
  getFontWeightLabels,
} from "../../../text-fonts.ts";
import { formatEms, formatMultiple, formatPixels } from "../../params.ts";
import type { FxEffectDefinition } from "../../types.ts";
import {
  DEFAULT_FONT_SIZE,
  DEFAULT_SHADOW_COLOR,
  DEFAULT_STROKE_COLOR,
  DEFAULT_TEXT,
  DEFAULT_TEXT_COLOR,
  DEFAULT_TEXT_GRADIENT,
  MAX_FONT_SIZE,
  MIN_FONT_SIZE,
  OFF_ON,
  TEXT_ALIGNS,
  TEXT_EFFECT_NAME,
  TEXT_FILL_MODES,
  TEXT_STYLE_FLAGS,
  TEXT_VERTICAL_ALIGNS,
} from "./text-style.ts";

// Where the effect sits in the add menus, lowest first.
export const menuOrder = 110;

export const definition: FxEffectDefinition = {
  effectName: TEXT_EFFECT_NAME,
  displayName: "Text",
  description: "Sets the words, font and look of a text clip.",
  accent: "#e8e4ff",
  category: "text",
  known: true,
  // Each text clip carries its own Text, so clips on one layer can say
  // different things.
  scopes: ["clip"],
  parameters: [
    { kind: "text", key: "Text", label: "Text", defaultValue: DEFAULT_TEXT },
    {
      kind: "font",
      key: "FontFamily",
      label: "Font",
      defaultValue: DEFAULT_FONT_FAMILY,
    },
    {
      kind: "enum",
      key: "FontWeight",
      label: "Weight",
      options: FONT_WEIGHT_LABELS,
      optionsFor: (read) => getFontWeightLabels(read("FontFamily")),
      menu: true,
      defaultValue: "Regular",
    },
    {
      kind: "flags",
      key: "FontStyle",
      label: "Style",
      options: TEXT_STYLE_FLAGS,
      defaultValue: "",
    },
    {
      kind: "enum",
      key: "Align",
      label: "Align",
      options: TEXT_ALIGNS,
      defaultValue: "Center",
    },
    {
      kind: "enum",
      key: "VerticalAlign",
      label: "Vertical",
      options: TEXT_VERTICAL_ALIGNS,
      defaultValue: "Middle",
    },
    {
      kind: "enum",
      key: "ResizeToFit",
      label: "Resize to fit",
      options: OFF_ON,
      defaultValue: "Off",
    },
    {
      kind: "enum",
      key: "FillMode",
      label: "Fill",
      options: TEXT_FILL_MODES,
      defaultValue: "Solid",
    },
    {
      kind: "color",
      key: "Color",
      label: "Color",
      defaultValue: DEFAULT_TEXT_COLOR,
      visibleWhen: { key: "FillMode", values: ["Solid"] },
    },
    {
      kind: "gradient",
      key: "Gradient",
      label: "Gradient",
      defaultValue: DEFAULT_TEXT_GRADIENT,
      visibleWhen: { key: "FillMode", values: ["Gradient"] },
    },
    {
      kind: "color",
      key: "Stroke",
      label: "Stroke Color",
      defaultValue: DEFAULT_STROKE_COLOR,
    },
    {
      kind: "enum",
      key: "Shadow",
      label: "Shadow",
      options: OFF_ON,
      defaultValue: "Off",
    },
    {
      kind: "color",
      key: "ShadowColor",
      label: "Shadow Color",
      defaultValue: DEFAULT_SHADOW_COLOR,
      visibleWhen: { key: "Shadow", values: ["On"] },
    },
    {
      kind: "number",
      key: "FontSize",
      label: "Size",
      min: MIN_FONT_SIZE,
      max: MAX_FONT_SIZE,
      defaultValue: DEFAULT_FONT_SIZE,
      step: 1,
      format: formatPixels,
    },
    {
      kind: "number",
      key: "LineHeight",
      label: "Leading",
      min: 0.6,
      max: 3,
      defaultValue: 1.2,
      step: 0.01,
      format: formatMultiple,
    },
    {
      kind: "number",
      key: "LetterSpacing",
      label: "Tracking",
      min: -0.2,
      max: 1,
      defaultValue: 0,
      step: 0.01,
      format: formatEms,
    },
    {
      kind: "number",
      key: "StrokeWidth",
      label: "Stroke",
      min: 0,
      max: 20,
      defaultValue: 0,
      step: 0.5,
      format: formatPixels,
    },
    {
      kind: "number",
      key: "Padding",
      label: "Padding",
      min: 0,
      max: 200,
      defaultValue: 0,
      step: 1,
      format: formatPixels,
    },
    {
      kind: "number",
      key: "ShadowBlur",
      label: "Blur",
      min: 0,
      max: 50,
      defaultValue: 8,
      step: 1,
      format: formatPixels,
      visibleWhen: { key: "Shadow", values: ["On"] },
    },
    {
      kind: "number",
      key: "ShadowOffsetX",
      label: "Shadow X",
      min: -50,
      max: 50,
      defaultValue: 4,
      step: 1,
      format: formatPixels,
      visibleWhen: { key: "Shadow", values: ["On"] },
    },
    {
      kind: "number",
      key: "ShadowOffsetY",
      label: "Shadow Y",
      min: -50,
      max: 50,
      defaultValue: 4,
      step: 1,
      format: formatPixels,
      visibleWhen: { key: "Shadow", values: ["On"] },
    },
  ],
};
