import { formatPercent } from "../../params.ts";
import type { FxEffectDefinition } from "../../types.ts";
import {
  DAMPING_DEFAULT,
  DAMPING_KEY,
  DAMPING_MAX,
  DAMPING_MIN,
  DECAY_DEFAULT,
  DECAY_KEY,
  DECAY_MAX,
  DECAY_MIN,
  formatDamping,
  formatDecay,
  formatPreDelay,
  MIX_DEFAULT,
  MIX_KEY,
  PRE_DELAY_DEFAULT_MS,
  PRE_DELAY_KEY,
  PRE_DELAY_MAX_MS,
  REVERB_EFFECT_NAME,
  SIZE_DEFAULT,
  SIZE_KEY,
} from "./reverb.ts";

export const menuOrder = 240;

export const definition: FxEffectDefinition = {
  effectName: REVERB_EFFECT_NAME,
  displayName: "Reverb",
  description: "Places the sound in a room or hall that rings after it.",
  accent: "#cbd5e1",
  domain: "audio",
  known: true,
  scopes: ["layer", "clip", "global"],
  parameters: [
    {
      kind: "number",
      key: DECAY_KEY,
      label: "Decay",
      min: DECAY_MIN,
      max: DECAY_MAX,
      defaultValue: DECAY_DEFAULT,
      step: 0.01,
      taper: "log",
      format: formatDecay,
    },
    {
      kind: "number",
      key: PRE_DELAY_KEY,
      label: "Pre-delay",
      min: 0,
      max: PRE_DELAY_MAX_MS,
      defaultValue: PRE_DELAY_DEFAULT_MS,
      step: 1,
      format: formatPreDelay,
    },
    {
      kind: "number",
      key: SIZE_KEY,
      label: "Size",
      min: 0,
      max: 1,
      defaultValue: SIZE_DEFAULT,
      step: 0.01,
      format: formatPercent,
    },
    {
      kind: "number",
      key: DAMPING_KEY,
      label: "Damping",
      min: DAMPING_MIN,
      max: DAMPING_MAX,
      defaultValue: DAMPING_DEFAULT,
      step: 1,
      taper: "log",
      format: formatDamping,
    },
    {
      kind: "number",
      key: MIX_KEY,
      label: "Mix",
      min: 0,
      max: 1,
      defaultValue: MIX_DEFAULT,
      step: 0.01,
      format: formatPercent,
    },
  ],
};
