[[permission]]
identifier = "allow-open-session"
description = "Enables the open_session command."
commands.allow = ["open_session"]

[[permission]]
identifier = "allow-list-font-families"
description = "Enables the list_font_families command."
commands.allow = ["list_font_families"]

[[permission]]
identifier = "allow-read-file-bytes"
description = "Enables the read_file_bytes command."
commands.allow = ["read_file_bytes"]

[[permission]]
identifier = "allow-read-file-prefix"
description = "Enables the read_file_prefix command."
commands.allow = ["read_file_prefix"]

[[permission]]
identifier = "allow-files-exist"
description = "Enables the files_exist command."
commands.allow = ["files_exist"]

[[permission]]
identifier = "allow-write-file-bytes"
description = "Enables the write_file_bytes command."
commands.allow = ["write_file_bytes"]

[[permission]]
identifier = "allow-mux-export"
description = "Enables the mux_export command."
commands.allow = ["mux_export"]

[default]
description = "Default application permissions."
permissions = [
  "allow-open-session",
  "allow-list-font-families",
  "allow-read-file-bytes",
  "allow-read-file-prefix",
  "allow-files-exist",
  "allow-write-file-bytes",
  "allow-mux-export",
]
