// Generated by scripts/gen-fx-index.mjs from the effect folders. Do not
// edit; run `pnpm --dir app run gen:fx-index` after adding an effect.

import type { EffectPass } from "../../fx-shaders/types.ts";
import type { FxEffectDefinitionModule } from "../types.ts";
import * as analogGlitch from "./analog-glitch/definition.ts";
import { pass as analogGlitchPass } from "./analog-glitch/pass.ts";
import * as autoPan from "./auto-pan/definition.ts";
import * as bitcrush from "./bitcrush/definition.ts";
import * as bloom from "./bloom/definition.ts";
import { pass as bloomPass } from "./bloom/pass.ts";
import * as caustics from "./caustics/definition.ts";
import { pass as causticsPass } from "./caustics/pass.ts";
import * as chorus from "./chorus/definition.ts";
import * as color from "./color/definition.ts";
import * as colorize from "./colorize/definition.ts";
import { pass as colorizePass } from "./colorize/pass.ts";
import * as compressor from "./compressor/definition.ts";
import * as deEss from "./de-ess/definition.ts";
import * as delay from "./delay/definition.ts";
import * as digitalGlitch from "./digital-glitch/definition.ts";
import { pass as digitalGlitchPass } from "./digital-glitch/pass.ts";
import * as distortion from "./distortion/definition.ts";
import { pass as distortionPass } from "./distortion/pass.ts";
import * as eq from "./eq/definition.ts";
import * as gain from "./gain/definition.ts";
import * as gaussianBlur from "./gaussian-blur/definition.ts";
import { pass as gaussianBlurPass } from "./gaussian-blur/pass.ts";
import * as highCut from "./high-cut/definition.ts";
import * as layout from "./layout/definition.ts";
import * as limiter from "./limiter/definition.ts";
import * as lowCut from "./low-cut/definition.ts";
import * as mask from "./mask/definition.ts";
import * as mono from "./mono/definition.ts";
import * as move from "./move/definition.ts";
import * as negativeSplit from "./negative-split/definition.ts";
import { pass as negativeSplitPass } from "./negative-split/pass.ts";
import * as noiseGate from "./noise-gate/definition.ts";
import * as order from "./order/definition.ts";
import * as phaser from "./phaser/definition.ts";
import * as pixelate from "./pixelate/definition.ts";
import { pass as pixelatePass } from "./pixelate/pass.ts";
import * as refraction from "./refraction/definition.ts";
import { pass as refractionPass } from "./refraction/pass.ts";
import * as reverb from "./reverb/definition.ts";
import * as reverse from "./reverse/definition.ts";
import * as saturation from "./saturation/definition.ts";
import * as shape from "./shape/definition.ts";
import { pass as shapePass } from "./shape/pass.ts";
import * as stereo from "./stereo/definition.ts";
import * as text from "./text/definition.ts";
import * as transform from "./transform/definition.ts";
import * as transientShaper from "./transient-shaper/definition.ts";
import * as tremolo from "./tremolo/definition.ts";
import * as zoomAndPan from "./zoom-and-pan/definition.ts";
import { pass as zoomAndPanPass } from "./zoom-and-pan/pass.ts";

// Every effect folder's definition.ts, in folder order.
export const EFFECT_DEFINITION_MODULES: readonly FxEffectDefinitionModule[] = [
  analogGlitch,
  autoPan,
  bitcrush,
  bloom,
  caustics,
  chorus,
  color,
  colorize,
  compressor,
  deEss,
  delay,
  digitalGlitch,
  distortion,
  eq,
  gain,
  gaussianBlur,
  highCut,
  layout,
  limiter,
  lowCut,
  mask,
  mono,
  move,
  negativeSplit,
  noiseGate,
  order,
  phaser,
  pixelate,
  refraction,
  reverb,
  reverse,
  saturation,
  shape,
  stereo,
  text,
  transform,
  transientShaper,
  tremolo,
  zoomAndPan,
];

// Every effect folder's pass.ts, in folder order.
export const EFFECT_PASSES: readonly EffectPass[] = [
  analogGlitchPass,
  bloomPass,
  causticsPass,
  colorizePass,
  digitalGlitchPass,
  distortionPass,
  gaussianBlurPass,
  negativeSplitPass,
  pixelatePass,
  refractionPass,
  shapePass,
  zoomAndPanPass,
];
