// Generated by scripts/gen-fx-index.mjs from the effect folders. Do not
// edit; run `pnpm --dir app run gen:fx-index` after adding an effect.

import type { EffectPass } from "../../fx-shaders/types.ts";
import type { FxEffectDefinitionModule } from "../types.ts";
import * as analogGlitch from "./analog-glitch/definition.ts";
import { pass as analogGlitchPass } from "./analog-glitch/pass.ts";
import * as chorus from "./chorus/definition.ts";
import * as color from "./color/definition.ts";
import * as colorize from "./colorize/definition.ts";
import { pass as colorizePass } from "./colorize/pass.ts";
import * as eq from "./eq/definition.ts";
import * as gain from "./gain/definition.ts";
import * as layout from "./layout/definition.ts";
import * as move from "./move/definition.ts";
import * as negativeSplit from "./negative-split/definition.ts";
import { pass as negativeSplitPass } from "./negative-split/pass.ts";
import * as order from "./order/definition.ts";
import * as pixelate from "./pixelate/definition.ts";
import { pass as pixelatePass } from "./pixelate/pass.ts";
import * as stereo from "./stereo/definition.ts";
import * as text from "./text/definition.ts";
import * as transform from "./transform/definition.ts";
import * as transientShaper from "./transient-shaper/definition.ts";
import * as zoomAndPan from "./zoom-and-pan/definition.ts";
import { pass as zoomAndPanPass } from "./zoom-and-pan/pass.ts";

// Every effect folder's definition.ts, in folder order.
export const EFFECT_DEFINITION_MODULES: readonly FxEffectDefinitionModule[] = [
  analogGlitch,
  chorus,
  color,
  colorize,
  eq,
  gain,
  layout,
  move,
  negativeSplit,
  order,
  pixelate,
  stereo,
  text,
  transform,
  transientShaper,
  zoomAndPan,
];

// Every effect folder's pass.ts, in folder order.
export const EFFECT_PASSES: readonly EffectPass[] = [
  analogGlitchPass,
  colorizePass,
  negativeSplitPass,
  pixelatePass,
  zoomAndPanPass,
];
