// Generated by scripts/gen-fx-index.mjs from the effect folders. Do not
// edit; run `pnpm --dir app run gen:fx-index` after adding an effect.

import type { AudioEffectDsp } from "../../audio-mix/processor.ts";
import { processor as chorusProcessor } from "./chorus/processor.ts";
import { processor as eqProcessor } from "./eq/processor.ts";
import { processor as gainProcessor } from "./gain/processor.ts";
import { processor as stereoProcessor } from "./stereo/processor.ts";

// Every audio effect folder's processor.ts, in folder order.
export const EFFECT_AUDIO_PROCESSORS: readonly AudioEffectDsp[] = [
  chorusProcessor,
  eqProcessor,
  gainProcessor,
  stereoProcessor,
];
