// Generated by scripts/gen-fx-index.mjs from the effect folders. Do not
// edit; run `pnpm --dir app run gen:fx-index` after adding an effect.

import type { AudioEffectDsp } from "../../audio-mix/processor.ts";
import { processor as autoPanProcessor } from "./auto-pan/processor.ts";
import { processor as bitcrushProcessor } from "./bitcrush/processor.ts";
import { processor as chorusProcessor } from "./chorus/processor.ts";
import { processor as compressorProcessor } from "./compressor/processor.ts";
import { processor as deEssProcessor } from "./de-ess/processor.ts";
import { processor as delayProcessor } from "./delay/processor.ts";
import { processor as eqProcessor } from "./eq/processor.ts";
import { processor as gainProcessor } from "./gain/processor.ts";
import { processor as highPassProcessor } from "./high-pass/processor.ts";
import { processor as limiterProcessor } from "./limiter/processor.ts";
import { processor as lowPassProcessor } from "./low-pass/processor.ts";
import { processor as monoProcessor } from "./mono/processor.ts";
import { processor as noiseGateProcessor } from "./noise-gate/processor.ts";
import { processor as phaserProcessor } from "./phaser/processor.ts";
import { processor as reverseProcessor } from "./reverse/processor.ts";
import { processor as saturationProcessor } from "./saturation/processor.ts";
import { processor as stereoProcessor } from "./stereo/processor.ts";
import { processor as transientShaperProcessor } from "./transient-shaper/processor.ts";
import { processor as tremoloProcessor } from "./tremolo/processor.ts";

// Every audio effect folder's processor.ts, in folder order.
export const EFFECT_AUDIO_PROCESSORS: readonly AudioEffectDsp[] = [
  autoPanProcessor,
  bitcrushProcessor,
  chorusProcessor,
  compressorProcessor,
  deEssProcessor,
  delayProcessor,
  eqProcessor,
  gainProcessor,
  highPassProcessor,
  limiterProcessor,
  lowPassProcessor,
  monoProcessor,
  noiseGateProcessor,
  phaserProcessor,
  reverseProcessor,
  saturationProcessor,
  stereoProcessor,
  transientShaperProcessor,
  tremoloProcessor,
];
