import { formatPercent } from "../../params.ts";
import type { FxEffectDefinition } from "../../types.ts";
import {
  DELAY_EFFECT_NAME,
  FEEDBACK_DEFAULT,
  FEEDBACK_KEY,
  FEEDBACK_MAX,
  formatHighCut,
  formatTimeMs,
  HIGH_CUT_DEFAULT,
  HIGH_CUT_KEY,
  HIGH_CUT_MAX,
  HIGH_CUT_MIN,
  MIX_DEFAULT,
  MIX_KEY,
  NOTE_DEFAULT,
  NOTE_KEY,
  NOTE_OPTIONS,
  OFF,
  ON,
  PING_PONG_DEFAULT,
  PING_PONG_KEY,
  SWITCH_OPTIONS,
  SYNC_DEFAULT,
  SYNC_KEY,
  TIME_DEFAULT_MS,
  TIME_KEY,
  TIME_MAX_MS,
  TIME_MIN_MS,
} from "./delay.ts";

export const menuOrder = 250;

export const definition: FxEffectDefinition = {
  effectName: DELAY_EFFECT_NAME,
  displayName: "Delay",
  description: "Repeats the sound as fading echoes, optionally on the beat.",
  accent: "#f9a8d4",
  category: "modulation",
  domain: "audio",
  known: true,
  scopes: ["layer", "clip", "global"],
  parameters: [
    {
      kind: "enum",
      key: SYNC_KEY,
      label: "Sync",
      options: SWITCH_OPTIONS,
      defaultValue: SYNC_DEFAULT,
    },
    {
      kind: "number",
      key: TIME_KEY,
      label: "Time",
      min: TIME_MIN_MS,
      max: TIME_MAX_MS,
      defaultValue: TIME_DEFAULT_MS,
      step: 1,
      format: formatTimeMs,
      visibleWhen: { key: SYNC_KEY, values: [OFF] },
    },
    {
      kind: "enum",
      key: NOTE_KEY,
      label: "Note",
      options: NOTE_OPTIONS,
      menu: true,
      defaultValue: NOTE_DEFAULT,
      visibleWhen: { key: SYNC_KEY, values: [ON] },
    },
    {
      kind: "number",
      key: FEEDBACK_KEY,
      label: "Feedback",
      min: 0,
      max: FEEDBACK_MAX,
      defaultValue: FEEDBACK_DEFAULT,
      step: 0.01,
      format: formatPercent,
    },
    {
      kind: "enum",
      key: PING_PONG_KEY,
      label: "Ping-pong",
      options: SWITCH_OPTIONS,
      defaultValue: PING_PONG_DEFAULT,
    },
    {
      kind: "number",
      key: HIGH_CUT_KEY,
      label: "High cut",
      min: HIGH_CUT_MIN,
      max: HIGH_CUT_MAX,
      defaultValue: HIGH_CUT_DEFAULT,
      step: 1,
      taper: "log",
      format: formatHighCut,
    },
    {
      kind: "number",
      key: MIX_KEY,
      label: "Mix",
      min: 0,
      max: 1,
      defaultValue: MIX_DEFAULT,
      step: 0.01,
      format: formatPercent,
    },
  ],
};
