import { formatPercent } from "../../params.ts";
import type { FxEffectDefinition } from "../../types.ts";
import {
  CHORUS_EFFECT_NAME,
  DELAY_DEFAULT_MS,
  DELAY_KEY,
  DELAY_MAX_MS,
  DELAY_MIN_MS,
  DEPTH_DEFAULT,
  DEPTH_KEY,
  FEEDBACK_DEFAULT,
  FEEDBACK_KEY,
  FEEDBACK_MAX,
  formatDelayMs,
  formatRate,
  MIX_DEFAULT,
  MIX_KEY,
  RATE_DEFAULT,
  RATE_KEY,
  RATE_MAX,
  RATE_MIN,
  SPREAD_DEFAULT,
  SPREAD_KEY,
} from "./chorus.ts";

export const menuOrder = 230;

export const definition: FxEffectDefinition = {
  effectName: CHORUS_EFFECT_NAME,
  displayName: "Chorus",
  description:
    "Thickens the sound with a short delay whose length a slow LFO sweeps.",
  accent: "#a78bfa",
  category: "modulation",
  domain: "audio",
  known: true,
  scopes: ["layer", "clip", "global"],
  parameters: [
    {
      kind: "number",
      key: RATE_KEY,
      label: "Rate",
      min: RATE_MIN,
      max: RATE_MAX,
      defaultValue: RATE_DEFAULT,
      step: 0.01,
      taper: "log",
      format: formatRate,
    },
    {
      kind: "number",
      key: DEPTH_KEY,
      label: "Depth",
      min: 0,
      max: 1,
      defaultValue: DEPTH_DEFAULT,
      step: 0.01,
      format: formatPercent,
    },
    {
      kind: "number",
      key: DELAY_KEY,
      label: "Delay",
      min: DELAY_MIN_MS,
      max: DELAY_MAX_MS,
      defaultValue: DELAY_DEFAULT_MS,
      step: 0.1,
      format: formatDelayMs,
    },
    {
      kind: "number",
      key: FEEDBACK_KEY,
      label: "Feedback",
      min: 0,
      max: FEEDBACK_MAX,
      defaultValue: FEEDBACK_DEFAULT,
      step: 0.01,
      format: formatPercent,
    },
    {
      kind: "number",
      key: SPREAD_KEY,
      label: "Spread",
      min: 0,
      max: 1,
      defaultValue: SPREAD_DEFAULT,
      step: 0.01,
      format: formatPercent,
    },
    {
      kind: "number",
      key: MIX_KEY,
      label: "Mix",
      min: 0,
      max: 1,
      defaultValue: MIX_DEFAULT,
      step: 0.01,
      format: formatPercent,
    },
  ],
};
