import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";
import {
  BUNDLED_LUT_GROUP,
  BUNDLED_LUTS,
  bundledLutUrl,
  findBundledLut,
} from "../src/fx/effects/lut/bundled.ts";
import { parseCubeLut, sampleCubeLut } from "../src/fx/effects/lut/cube.ts";
import {
  CREDITS_PATH,
  LOOKS,
  LUT_SIZE,
  LUTS_DIR,
  renderAll,
} from "./gen-film-luts.mjs";

const read = (file) => readFileSync(file, "utf8").replace(/\r\n/g, "\n");
const parse = (lut) => parseCubeLut(read(join(LUTS_DIR, lut.file)));

// Samples a look at a few representative colors.
const PROBES = [
  [0.05, 0.05, 0.05],
  [0.5, 0.5, 0.5],
  [0.95, 0.95, 0.95],
  [0.8, 0.3, 0.2],
  [0.2, 0.6, 0.3],
  [0.2, 0.3, 0.8],
  [0.85, 0.65, 0.5],
];
const sample = (look) => PROBES.flatMap((rgb) => look(rgb));
const distance = (a, b) =>
  Math.max(...a.map((value, index) => Math.abs(value - b[index])));

describe("bundled LUTs", () => {
  it("have unique stable ids, names and files", () => {
    const ids = BUNDLED_LUTS.map((lut) => lut.id);
    assert.equal(new Set(ids).size, ids.length);
    assert.equal(new Set(BUNDLED_LUTS.map((lut) => lut.name)).size, ids.length);
    assert.equal(new Set(BUNDLED_LUTS.map((lut) => lut.file)).size, ids.length);
    for (const lut of BUNDLED_LUTS) {
      assert.match(lut.id, /^builtin:[a-z0-9-]+$/);
      assert.equal(findBundledLut(lut.id), lut);
      assert.equal(findBundledLut(` ${lut.id.toUpperCase()} `), lut);
    }
    assert.equal(BUNDLED_LUT_GROUP, "Built-in");
    assert.equal(findBundledLut("builtin:missing"), undefined);
    assert.equal(findBundledLut("Sepia"), undefined);
    assert.equal(findBundledLut(undefined), undefined);
  });

  it("resolve every id to its bundled file", () => {
    for (const lut of BUNDLED_LUTS) {
      assert.equal(bundledLutUrl(lut), `/luts/${lut.file}`);
    }
    assert.equal(
      bundledLutUrl(findBundledLut("builtin:sepia")),
      "/luts/sepia.cube",
    );
  });

  it("bundle exactly one file per id plus CREDITS.md", () => {
    const files = readdirSync(LUTS_DIR).sort();
    const expected = [...BUNDLED_LUTS.map((lut) => lut.file), "CREDITS.md"];
    assert.deepEqual(files, expected.sort());
  });

  it("match the generator's output", () => {
    for (const [file, expected] of renderAll()) {
      assert.equal(read(file), expected, `${file} is stale`);
    }
  });

  it("parse with the .cube parser at 33³ or smaller", () => {
    assert.ok(LUT_SIZE <= 33);
    for (const lut of BUNDLED_LUTS) {
      const cube = parse(lut);
      assert.equal(cube.title, lut.name);
      assert.equal(cube.size, LUT_SIZE);
      assert.equal(cube.data.length, LUT_SIZE ** 3 * 3);
    }
  });

  it("grade like their looks through the LUT's interpolation", () => {
    for (const lut of BUNDLED_LUTS) {
      const cube = parse(lut);
      const graded = PROBES.flatMap((rgb) => sampleCubeLut(cube, rgb));
      assert.ok(
        distance(graded, sample(LOOKS[lut.id])) < 0.02,
        `${lut.id} drifts from its look`,
      );
    }
  });

  it("each visibly and distinctly grade the picture", () => {
    const identity = sample((rgb) => rgb);
    const samples = BUNDLED_LUTS.map((lut) => [lut.id, sample(LOOKS[lut.id])]);
    for (const [id, values] of samples) {
      assert.ok(
        distance(values, identity) > 0.05,
        `${id} barely changes color`,
      );
    }
    for (let i = 0; i < samples.length; i += 1) {
      for (let j = i + 1; j < samples.length; j += 1) {
        assert.ok(
          distance(samples[i][1], samples[j][1]) > 0.04,
          `${samples[i][0]} and ${samples[j][0]} look alike`,
        );
      }
    }
  });

  it("list every file in CREDITS.md with its license", () => {
    const credits = read(CREDITS_PATH);
    for (const lut of BUNDLED_LUTS) {
      const row = credits
        .split("\n")
        .find((line) => line.startsWith(`| \`${lut.file}\` |`));
      assert.ok(row, `${lut.file} is missing from CREDITS.md`);
      assert.match(row, /Generated by zvid/);
    }
  });
});
