import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";
import {
  BUILTIN_LUTS,
  builtinLutUrl,
  findBuiltinLut,
  isBuiltinLutId,
} from "../src/fx/effects/lut/builtin-luts.ts";
import {
  CREDITS_PATH,
  LOOKS,
  LUT_SIZE,
  LUTS_DIR,
  renderAll,
} from "./gen-film-luts.mjs";

const read = (file) => readFileSync(file, "utf8").replace(/\r\n/g, "\n");

// Samples a look at a few representative colors.
const PROBES = [
  [0.05, 0.05, 0.05],
  [0.5, 0.5, 0.5],
  [0.95, 0.95, 0.95],
  [0.8, 0.3, 0.2],
  [0.2, 0.6, 0.3],
  [0.2, 0.3, 0.8],
  [0.85, 0.65, 0.5],
];
const sample = (look) => PROBES.flatMap((rgb) => look(rgb));
const distance = (a, b) =>
  Math.max(...a.map((value, index) => Math.abs(value - b[index])));

describe("built-in LUTs", () => {
  it("have unique stable ids, names and files", () => {
    const ids = BUILTIN_LUTS.map((lut) => lut.id);
    assert.equal(new Set(ids).size, ids.length);
    assert.equal(new Set(BUILTIN_LUTS.map((lut) => lut.name)).size, ids.length);
    assert.equal(new Set(BUILTIN_LUTS.map((lut) => lut.file)).size, ids.length);
    for (const lut of BUILTIN_LUTS) {
      assert.match(lut.id, /^builtin:[a-z0-9-]+$/);
      assert.ok(isBuiltinLutId(lut.id));
      assert.equal(findBuiltinLut(lut.id), lut);
    }
    assert.equal(findBuiltinLut("builtin:missing"), undefined);
    assert.equal(isBuiltinLutId("media:abc"), false);
  });

  it("resolve every id to a bundled file URL", () => {
    const lut = findBuiltinLut("builtin:sepia");
    assert.equal(builtinLutUrl(lut), "/luts/sepia.cube");
    assert.equal(builtinLutUrl(lut, "/app"), "/app/luts/sepia.cube");
  });

  it("bundle exactly one file per id plus CREDITS.md", () => {
    const files = readdirSync(LUTS_DIR).sort();
    const expected = [...BUILTIN_LUTS.map((lut) => lut.file), "CREDITS.md"];
    assert.deepEqual(files, expected.sort());
  });

  it("match the generator's output", () => {
    for (const [file, expected] of renderAll()) {
      assert.equal(read(file), expected, `${file} is stale`);
    }
  });

  it("are well-formed .cube files of at most 33³", () => {
    for (const lut of BUILTIN_LUTS) {
      const lines = read(join(LUTS_DIR, lut.file)).trimEnd().split("\n");
      assert.ok(lines.includes(`LUT_3D_SIZE ${LUT_SIZE}`));
      assert.ok(LUT_SIZE <= 33);
      const rows = lines.filter((line) => /^[\d.]+ [\d.]+ [\d.]+$/.test(line));
      assert.equal(rows.length, LUT_SIZE ** 3, lut.file);
      for (const row of rows) {
        for (const value of row.split(" ").map(Number)) {
          assert.ok(value >= 0 && value <= 1, `${lut.file}: ${row}`);
        }
      }
    }
  });

  it("each visibly and distinctly grade the picture", () => {
    const identity = sample((rgb) => rgb);
    const samples = BUILTIN_LUTS.map((lut) => [lut.id, sample(LOOKS[lut.id])]);
    for (const [id, values] of samples) {
      assert.ok(
        distance(values, identity) > 0.05,
        `${id} barely changes color`,
      );
    }
    for (let i = 0; i < samples.length; i += 1) {
      for (let j = i + 1; j < samples.length; j += 1) {
        assert.ok(
          distance(samples[i][1], samples[j][1]) > 0.04,
          `${samples[i][0]} and ${samples[j][0]} look alike`,
        );
      }
    }
  });

  it("list every file in CREDITS.md with its license", () => {
    const credits = read(CREDITS_PATH);
    for (const lut of BUILTIN_LUTS) {
      const row = credits
        .split("\n")
        .find((line) => line.startsWith(`| \`${lut.file}\` |`));
      assert.ok(row, `${lut.file} is missing from CREDITS.md`);
      assert.match(row, /Generated by zvid/);
    }
  });
});
